version: 'latest'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
  db:
    image: mongo:latest
    volumes:
      - ./mongo-data:/data/db
